name: Compile the showcases
'on':
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2
      with:
        lfs: true
        submodules: true
    - name: Setup Python environment for sltx
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Setup and run sltx-install
      run: |
        pip install sltx
        echo "tx-default" | sltx docker
    - name: Install PU for previews
      run: sudo apt install poppler-utils
    - name: Compile the Documents
      run: |
        sltx compile --root --recipe 'default-latexmk.recipe' --profile "tx-default" "test.tex"
    - name: 🖼️ Generate preview
      run: |
         pdftoppm -png -r 300 -f 37 -l 37 ./noanim_ecmfa2023-presentation.pdf preview
    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f "test.pdf" "preview-*.png"
        git commit -m "Newly compiled data"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
